// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HbDslaT9P5CwWkKmYeW9MrllDkA4BPY',
    appId: '1:597540165276:web:f35c87a5b2dea018c53f59',
    messagingSenderId: '597540165276',
    projectId: 'stockapp-7250e',
    authDomain: 'stockapp-7250e.firebaseapp.com',
    storageBucket: 'stockapp-7250e.appspot.com',
    measurementId: 'G-Q8KPZX1MMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAslTiBlK0ueJDxUtnhbMAagF71lpyf94',
    appId: '1:597540165276:android:c43cec24c498289ac53f59',
    messagingSenderId: '597540165276',
    projectId: 'stockapp-7250e',
    storageBucket: 'stockapp-7250e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiunqUSVXi6l67WCQxVZzMORc9FwqqUQ4',
    appId: '1:597540165276:ios:edfd1dfdea4cc20bc53f59',
    messagingSenderId: '597540165276',
    projectId: 'stockapp-7250e',
    storageBucket: 'stockapp-7250e.appspot.com',
    iosClientId: '597540165276-65c5e49koqavoq7nr1ptgfhlavpo25jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );
}
